# DAY12:-NUMPY LIBRARY

It is open source library and it has ability to perform mathematical operations on numerical data set.

It contains a multidimensional array and matrix data structure.

The array object in NumPy is called ndarray which provide a lot of supporting functions that make working with ndarray very easy.

In [10]:
import numpy as np

In [11]:
arr=np.array([1,2,3,4,5,6])
print(arr)
print(type(arr))

[1 2 3 4 5 6]
<class 'numpy.ndarray'>


In [12]:
arr=np.array((1,2,3,4,5))
print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


# Dimensions in array

0D Element ARRAY

In [13]:
arr=np.array(20)
print(arr)
print(type(arr))
print(arr.ndim)

20
<class 'numpy.ndarray'>
0


1D ARRAY

In [14]:
arr=np.array((1,2,3,4,5,6))
print(arr)
print(arr.ndim)

[1 2 3 4 5 6]
1


2D ARRAY

In [16]:
arr = np.array([[1,2,3,],[2,3,4]])
print(arr)
print(arr.ndim)

[[1 2 3]
 [2 3 4]]
2


In [17]:
arr = np.array([[1.2,2.2,3.2],[2.3,3.4,4.7]])
print(arr)
print(arr.ndim)

[[1.2 2.2 3.2]
 [2.3 3.4 4.7]]
2


3D ARRAY

In [18]:
arr = np.array([[[1,2,3],[4,5,6,]],[[1,2,3],[7,8,9]]])
print(arr)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [7 8 9]]]


# ALL IN ONE ARRAY

In [20]:
a=np.array(1)
b=np.array([1,2,3])
c=np.array([[1,2,3],[4,5,6]])
d=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[0,1,2]]])
print(a,b,c,d)
print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

1 [1 2 3] [[1 2 3]
 [4 5 6]] [[[1 2 3]
  [4 5 6]]

 [[7 8 9]
  [0 1 2]]]
0
1
2
3


# HIGHER DIMENSIONAL ARRAYS

An array having any number of dimension

When an array is created,you can define number of dimensions by using the ndim argument

# Creating array of 5 dimensions

In [24]:
arr=np.array([1,2,3,4],ndmin=5)
print(arr)
print('number of dimensions:',arr.ndim)

[[[[[1 2 3 4]]]]]
number of dimensions: 5


# NumPy Array Indexing

Array is the same as accessing an array element

You can access an array element by referring to its index number.

The indexes in NumPy arrays start with 0,meaning that the first element has index 0,and the second has index 1 etc.

# 1D ARRAY

# Get the first element of following array:

In [29]:
arr=np.array([1,2,3,4])
print(arr[0])

1


# Get 3,6,8 element from an array and add them

In [30]:
m=np.array([1,2,3,4,5,6,7,8,9,10])
print('3rd element:',m[3])
print('6th element:',m[6])
print('8th element:',m[8])
print('sum of the elements are',m[3]+m[6]+m[8])

3rd element: 4
6th element: 7
8th element: 9
sum of the elements are 20


# 2D ARRAY

In [31]:
arr=np.array([[1,2,3,4,5],[6,7,8,9,0]])
print(arr)

[[1 2 3 4 5]
 [6 7 8 9 0]]


In [33]:
arr=np.array([[1,2,3,4,5],[6,7,8,9,0]])
print(arr[1,0])
print(arr[0,4])

6
5


# add the first element of row 1 and last element

In [35]:
arr=np.array([[1,2,3,4,5],[6,7,8,9,0]])
print('sum is: ', arr[0,0]+arr[1,4])

sum is:  1


# ACCESS 3D ARRAYS:

In [37]:
arr=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(arr[0,1,2])
print(arr[1,0,0])

6
7
